plugins:
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-rails: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "bin/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
